apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec:
  selector:
    matchLabels:
      app: todo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: dotnet-todo-app
        image: arigsela/todo-app:80
        ports:
        - containerPort: 80
